### ISSUE TITLE
IDE is not Opening in ubuntu

### ISSUE THREAD

**Issue by criscros-garcia** [learn-co-curriculum/ttt-2-board-rb#30]

**Comment by maxwellbenton** [comment]
Hi @criscros-garcia,

Sorry to hear you were having difficulty getting this lab to open in Ubuntu. Unfortunately, I am unable to replicate this issue, but it sounds like it may have been due to an issue with the Learn platform. If you are still working on any Learn lessons and continue to experience these issues, please reach out to support@learn.co for further assistance.

Thank you!
